function [selectedCandidateIndex, evaluatedCandidates] = rerankPlateCandidates(inputImage, detectorCandidates, config)
    %RERANKPLATECANDIDATES Evaluate top detector candidates end-to-end and rerank them.
    
    config = validateConfig(config);
    evaluatedCandidates = localEmptyEvaluatedCandidates();
    
    if nargin < 2 || isempty(detectorCandidates)
        selectedCandidateIndex = [];
        return;
    end
    
    numCandidates = min(numel(detectorCandidates), config.reranking.maxCandidatesToEvaluate);
    imageSize = size(inputImage);
    
    for i = 1:numCandidates
        detectorCandidate = localNormalizeCandidate(detectorCandidates(i));
        paddedBBox = localPadBBox(detectorCandidate.bbox, imageSize, config.detection.platePadding);
    
        [rectifiedPlate, rectifyMeta] = rectifyPlate(inputImage, paddedBBox, config);
        [characterImages, characterBBoxes, segmentMeta] = segmentCharacters(rectifiedPlate, config);
        [recognizedText, recognitionMeta] = recognizeCharacters(characterImages, config, rectifiedPlate);
    
        stateLookupText = string(recognizedText);
        if isfield(recognitionMeta, "stateLookupText") && strlength(recognitionMeta.stateLookupText) > 0
            stateLookupText = recognitionMeta.stateLookupText;
        end
    
        stateInfo = identifyState(stateLookupText, config.malaysiaRules);
        [scoreBreakdown, finalScore] = localScoreEvaluatedCandidate( ...
            detectorCandidate, characterImages, segmentMeta, recognitionMeta, recognizedText, stateInfo, config);
    
        evaluatedCandidates(end+1) = struct( ... %#ok<AGROW>
            "candidateIndex", i, ...
            "bbox", paddedBBox, ...
            "rawBBox", detectorCandidate.bbox, ...
            "branchName", detectorCandidate.branchName, ...
            "profileName", detectorCandidate.profileName, ...
            "scale", detectorCandidate.scale, ...
            "detectorScore", detectorCandidate.score, ...
            "characterTextureScore", localGetCandidateField(detectorCandidate, "characterTextureScore"), ...
            "plateContrastScore", localGetCandidateField(detectorCandidate, "plateContrastScore"), ...
            "componentAlignmentScore", localGetCandidateField(detectorCandidate, "componentAlignmentScore"), ...
            "vehiclePositionScore", localGetCandidateField(detectorCandidate, "vehiclePositionScore"), ...
            "recognizedText", string(recognizedText), ...
            "stateLookupText", stateLookupText, ...
            "stateInfo", stateInfo, ...
            "characterCount", numel(characterImages), ...
            "characterImages", {characterImages}, ...
            "characterBBoxes", characterBBoxes, ...
            "rectifiedPlate", rectifiedPlate, ...
            "rectifyMeta", rectifyMeta, ...
            "segmentMeta", segmentMeta, ...
            "recognitionMeta", recognitionMeta, ...
            "segmentationScore", scoreBreakdown.segmentation, ...
            "recognitionScore", scoreBreakdown.recognition, ...
            "regexScore", scoreBreakdown.regex, ...
            "stateScore", scoreBreakdown.state, ...
            "emptyPenalty", scoreBreakdown.penalty, ...
            "scoreBreakdown", scoreBreakdown, ...
            "finalScore", finalScore, ...
            "selectionReason", localSelectionReason(scoreBreakdown, string(recognizedText), stateInfo));
    end
    
    if isempty(evaluatedCandidates)
        selectedCandidateIndex = [];
        return;
    end
    
    [~, sortIdx] = sort([evaluatedCandidates.finalScore], "descend");
    evaluatedCandidates = evaluatedCandidates(sortIdx);
    selectedCandidateIndex = 1;
end
    
function detectorCandidate = localNormalizeCandidate(candidate)
    detectorCandidate = struct( ...
        "bbox", [], ...
        "score", 0, ...
        "branchName", "unknown", ...
        "profileName", "unknown", ...
        "scale", 1.0, ...
        "characterTextureScore", 0, ...
        "plateContrastScore", 0, ...
        "componentAlignmentScore", 0, ...
        "vehiclePositionScore", 0, ...
        "emptyRegionPenalty", 1);
    
    fields = fieldnames(candidate);
    for i = 1:numel(fields)
        detectorCandidate.(fields{i}) = candidate.(fields{i});
    end
end
    
function [scoreBreakdown, finalScore] = localScoreEvaluatedCandidate(detectorCandidate, characterImages, segmentMeta, recognitionMeta, recognizedText, stateInfo, config)
    detectorScore = max(0, min(1, detectorCandidate.score));
    plateEvidenceScore = localDetectorEvidenceScore(detectorCandidate);
    segmentationScore = localSegmentationScore(numel(characterImages), segmentMeta, config);
    
    if isempty(recognitionMeta.confidences)
        recognitionScore = 0;
    else
        recognitionScore = max(0, min(1, mean(recognitionMeta.confidences)));
    end
    
    [regexScore, regexLabel] = localRegexScore(string(recognizedText), config);
    stateScore = localStateScore(stateInfo, string(recognizedText));
    
    weights = config.reranking.weights;
    baseScore = weights.detector * detectorScore + ...
        weights.plateEvidence * plateEvidenceScore + ...
        weights.segmentation * segmentationScore + ...
        weights.recognition * recognitionScore + ...
        weights.regex * regexScore + ...
        weights.state * stateScore;
    
    penalty = 0;
    characterCount = numel(characterImages);
    if characterCount == 0 || strlength(string(recognizedText)) == 0
        penalty = penalty + config.reranking.emptyCandidatePenalty;
    elseif characterCount <= 1
        penalty = penalty + config.reranking.lowCharacterPenalty;
    end
    if segmentationScore < 0.25
        penalty = penalty + config.reranking.weakSegmentationPenalty;
    end
    if plateEvidenceScore < 0.25
        penalty = penalty + config.reranking.weakTexturePenalty;
    end
    
    bonus = 0;
    switch regexLabel
        case "exact"
            bonus = bonus + config.reranking.regexExactBonus;
        case "partial"
            bonus = bonus + config.reranking.regexPartialBonus;
    end
    
    finalScore = max(0, min(1, baseScore + bonus - penalty));
    scoreBreakdown = struct( ...
        "detector", detectorScore, ...
        "plateEvidence", plateEvidenceScore, ...
        "characterTexture", localGetCandidateField(detectorCandidate, "characterTextureScore"), ...
        "plateContrast", localGetCandidateField(detectorCandidate, "plateContrastScore"), ...
        "componentAlignment", localGetCandidateField(detectorCandidate, "componentAlignmentScore"), ...
        "vehiclePosition", localGetCandidateField(detectorCandidate, "vehiclePositionScore"), ...
        "segmentation", segmentationScore, ...
        "recognition", recognitionScore, ...
        "regex", regexScore, ...
        "regexLabel", string(regexLabel), ...
        "state", stateScore, ...
        "bonus", bonus, ...
        "penalty", penalty, ...
        "final", finalScore);
end
    
function score = localSegmentationScore(characterCount, segmentMeta, config)
    expectedRange = config.reranking.expectedCharacterRange;
    if characterCount == 0
        countScore = 0;
    elseif characterCount >= expectedRange(1) && characterCount <= expectedRange(2)
        countScore = 1.0;
    elseif characterCount >= 2 && characterCount <= 10
        distance = min(abs(characterCount - expectedRange(1)), abs(characterCount - expectedRange(2)));
        countScore = max(0.35, 0.85 - 0.10 * distance);
    else
        countScore = 0.15;
    end
    
    qualityScore = 0;
    if nargin >= 2 && isstruct(segmentMeta) && isfield(segmentMeta, "qualityScore")
        qualityScore = max(0, min(1, segmentMeta.qualityScore));
    end
    if qualityScore > 0
        score = 0.45 * countScore + 0.55 * qualityScore;
    else
        score = countScore;
    end
end
    
function [score, label] = localRegexScore(recognizedText, config)
    normalized = upper(regexprep(string(recognizedText), "[^A-Z0-9]", ""));
    label = "none";
    
    if strlength(normalized) == 0
        score = 0;
        return;
    end
    
    exactPattern = "^[A-Z]{1,3}[0-9]{1,4}[A-Z]?$";
    partialPattern = "^[A-Z]{1,3}[0-9]{1,4}.*$";
    
    if ~isempty(regexp(normalized, exactPattern, "once"))
        score = 1.0;
        label = "exact";
    elseif ~isempty(regexp(normalized, partialPattern, "once"))
        score = 0.60;
        label = "partial";
    elseif any(startsWith(normalized, string({config.malaysiaRules.token})))
        score = 0.40;
        label = "prefix";
    else
        score = 0.05;
    end
end
    
function score = localStateScore(stateInfo, recognizedText)
    if isfield(stateInfo, "matched") && stateInfo.matched
        score = 1.0;
    elseif strlength(recognizedText) > 0
        score = 0.20;
    else
        score = 0;
    end
end
    
function reason = localSelectionReason(scoreBreakdown, recognizedText, stateInfo)
    reason = "Detector=" + sprintf("%.2f", scoreBreakdown.detector) + ...
        ", Plate=" + sprintf("%.2f", scoreBreakdown.plateEvidence) + ...
        ", Seg=" + sprintf("%.2f", scoreBreakdown.segmentation) + ...
        ", Rec=" + sprintf("%.2f", scoreBreakdown.recognition) + ...
        ", Regex=" + string(scoreBreakdown.regexLabel) + ...
        ", State=" + string(stateInfo.name) + ...
        ", Text=" + string(recognizedText);
end
    
function score = localDetectorEvidenceScore(detectorCandidate)
    characterTexture = localGetCandidateField(detectorCandidate, "characterTextureScore");
    plateContrast = localGetCandidateField(detectorCandidate, "plateContrastScore");
    alignment = localGetCandidateField(detectorCandidate, "componentAlignmentScore");
    position = localGetCandidateField(detectorCandidate, "vehiclePositionScore");
    emptyPenalty = localGetCandidateField(detectorCandidate, "emptyRegionPenalty");
    
    score = mean([characterTexture plateContrast alignment position]);
    score = max(0, min(1, score - 0.35 * emptyPenalty));
end
    
function value = localGetCandidateField(candidate, fieldName)
    value = 0;
    if isfield(candidate, fieldName)
        value = candidate.(fieldName);
    end
    value = max(0, min(1, double(value)));
end
    
function bbox = localPadBBox(bbox, imageSize, paddingRatio)
    paddingX = bbox(3) * paddingRatio;
    paddingY = bbox(4) * paddingRatio;
    
    x1 = max(1, floor(bbox(1) - paddingX));
    y1 = max(1, floor(bbox(2) - paddingY));
    x2 = min(imageSize(2), ceil(bbox(1) + bbox(3) + paddingX));
    y2 = min(imageSize(1), ceil(bbox(2) + bbox(4) + paddingY));
    bbox = [x1 y1 max(1, x2 - x1) max(1, y2 - y1)];
end
    
function records = localEmptyEvaluatedCandidates()
    records = struct( ...
        "candidateIndex", {}, ...
        "bbox", {}, ...
        "rawBBox", {}, ...
        "branchName", {}, ...
        "profileName", {}, ...
        "scale", {}, ...
        "detectorScore", {}, ...
        "characterTextureScore", {}, ...
        "plateContrastScore", {}, ...
        "componentAlignmentScore", {}, ...
        "vehiclePositionScore", {}, ...
        "recognizedText", {}, ...
        "stateLookupText", {}, ...
        "stateInfo", {}, ...
        "characterCount", {}, ...
        "characterImages", {}, ...
        "characterBBoxes", {}, ...
        "rectifiedPlate", {}, ...
        "rectifyMeta", {}, ...
        "segmentMeta", {}, ...
        "recognitionMeta", {}, ...
        "segmentationScore", {}, ...
        "recognitionScore", {}, ...
        "regexScore", {}, ...
        "stateScore", {}, ...
        "emptyPenalty", {}, ...
        "scoreBreakdown", {}, ...
        "finalScore", {}, ...
        "selectionReason", {});
end
