function config = defaultConfig(rootDir)
    %DEFAULTCONFIG Default settings for the LPR and state identification system.

    if nargin < 1 || strlength(string(rootDir)) == 0
        rootDir = fileparts(fileparts(fileparts(mfilename("fullpath"))));
    end

    config = struct();
    config.projectRoot = string(rootDir);

    config.paths = struct( ...
        "dataRoot", fullfile(rootDir, "data"), ...
        "rawData", fullfile(rootDir, "data", "raw"), ...
        "annotations", fullfile(rootDir, "data", "annotations"), ...
        "models", fullfile(rootDir, "models"), ...
        "trainedModels", fullfile(rootDir, "models", "trained"), ...
        "templates", fullfile(rootDir, "models", "templates"), ...
        "results", fullfile(rootDir, "experiments", "results"));

    config.preprocessing = struct( ...
        "medianFilterSize", [3 3], ...
        "contrastMethod", "hybrid", ...
        "claheTiles", [8 8], ...
        "claheClipLimit", 0.015, ...
        "gaussianSigma", 0.8);

    config.detection = struct( ...
        "edgeMethod", "Canny", ...
        "scales", [1.0 1.25 1.50], ...
        "minAreaRatio", 0.0003, ...
        "maxAreaRatio", 0.18, ...
        "minVerticalCenterRatio", 0.18, ...
        "maxVerticalCenterRatio", 0.96, ...
        "minHorizontalCenterRatio", 0.05, ...
        "maxHorizontalCenterRatio", 0.95, ...
        "minWidthRatio", 0.03, ...
        "maxWidthRatio", 0.65, ...
        "minHeightRatio", 0.01, ...
        "maxHeightRatio", 0.25, ...
        "minCandidateAreaPixels", 45, ...
        "maxCandidatesToKeep", 25, ...
        "closeKernel", [5 19], ...
        "openKernel", [3 7], ...
        "dilateKernel", [3 13], ...
        "minExtent", 0.10, ...
        "minSolidity", 0.10, ...
        "platePadding", 0.05, ...
        "priorityRoi", [0.15 0.45 0.85 0.95], ...
        "targetVerticalCenterRatio", 0.76, ...
        "targetHorizontalCenterRatio", 0.50);

    config.detection.profiles = [ ...
        struct( ...
            "name", "single_line", ...
            "targetAspectRatio", 4.0, ...
            "minAspectRatio", 2.8, ...
            "maxAspectRatio", 6.8, ...
            "targetWidthRatio", 0.26, ...
            "minWidthRatio", 0.11, ...
            "maxWidthRatio", 0.52, ...
            "targetHeightRatio", 0.065, ...
            "minHeightRatio", 0.025, ...
            "maxHeightRatio", 0.12, ...
            "targetAreaRatio", 0.015, ...
            "minAreaRatio", 0.002, ...
            "maxAreaRatio", 0.055), ...
        struct( ...
            "name", "motorcycle_small", ...
            "targetAspectRatio", 1.9, ...
            "minAspectRatio", 1.1, ...
            "maxAspectRatio", 3.2, ...
            "targetWidthRatio", 0.14, ...
            "minWidthRatio", 0.05, ...
            "maxWidthRatio", 0.28, ...
            "targetHeightRatio", 0.085, ...
            "minHeightRatio", 0.025, ...
            "maxHeightRatio", 0.16, ...
            "targetAreaRatio", 0.008, ...
            "minAreaRatio", 0.0008, ...
            "maxAreaRatio", 0.025), ...
        struct( ...
            "name", "two_row", ...
            "targetAspectRatio", 1.7, ...
            "minAspectRatio", 1.0, ...
            "maxAspectRatio", 3.0, ...
            "targetWidthRatio", 0.18, ...
            "minWidthRatio", 0.08, ...
            "maxWidthRatio", 0.34, ...
            "targetHeightRatio", 0.11, ...
            "minHeightRatio", 0.04, ...
            "maxHeightRatio", 0.20, ...
            "targetAreaRatio", 0.010, ...
            "minAreaRatio", 0.001, ...
            "maxAreaRatio", 0.035)
        ];

config.rectification = struct( ...
    "maxRotationDegrees", 12, ... 
    "tightCropPadding", 6, ...
    "cropPaddingRatio", 0.08, ...
    "minAngleConfidence", 0.32, ...
    "minLineLength", 18);

config.segmentation = struct( ...
    "foregroundPolarity", "dark", ...
    "adaptiveSensitivity", 0.48, ...
        "minAreaRatio", 0.010, ...
        "maxAreaRatio", 0.25, ...
        "minHeightRatio", 0.35, ...
        "maxHeightRatio", 0.96, ...
        "minWidthRatio", 0.02, ...
        "maxWidthRatio", 0.24, ...
        "minAspectRatio", 0.15, ...
        "maxAspectRatio", 1.15, ...
        "clearBorder", true, ...
        "minCharacters", 2, ...
        "maxCharacters", 10, ...
        "minComponentArea", 12, ...
        "openKernel", [2 2], ...
        "closeKernel", [3 3], ...
        "innerCropRatioX", 0.03, ...
        "innerCropRatioY", 0.06, ...
        "splitMinWidthRatio", 0.16, ...
    "splitMinAspectRatio", 0.90, ...
    "splitMinForegroundDip", 0.28, ...
    "splitMinColumnGap", 2, ...
    "rejectBorderTouchingTallComponents", true, ...
    "twoRowCenterGapRatio", 0.18, ...
    "projectionForegroundThreshold", 0.18, ...
    "horizontalBorderWidthRatio", 0.55, ...
    "horizontalBorderHeightRatio", 0.22);

    config.features = struct( ...
        "characterImageSize", [48 24], ...
        "hogCellSize", [4 4]);

    config.classification = struct( ...
        "method", "feature_classifier", ...
        "trainedModelPath", fullfile(rootDir, "models", "trained", "baselineCharacterModel.mat"), ...
        "autoTrainIfMissing", true, ...
        "kNeighbors", 3, ...
        "syntheticFonts", {{'Consolas','Arial','Tahoma','Verdana','Segoe UI'}}, ...
        "syntheticFontSize", 28, ...
        "syntheticCanvasSize", [64 64], ...
        "syntheticRotationDegrees", [-3 0 3], ...
        "topCandidatesPerCharacter", 5, ...
        "ambiguityPenalty", 0.04, ...
        "invalidPatternPenalty", 0.18, ...
        "allowedPrefixLengths", [1 2 3], ...
        "allowedDigitLengths", [1 2 3 4], ...
        "allowSuffixLetter", true, ...
        "characterSet", "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", ...
        "minimumConfidence", 0.05);

    config.reranking = struct( ...
        "maxCandidatesToEvaluate", 5, ...
        "expectedCharacterRange", [4 8], ...
        "weights", struct( ...
            "detector", 0.18, ...
            "plateEvidence", 0.18, ...
            "segmentation", 0.20, ...
            "recognition", 0.18, ...
            "regex", 0.14, ...
            "state", 0.12), ...
        "emptyCandidatePenalty", 0.55, ...
        "lowCharacterPenalty", 0.30, ...
        "weakSegmentationPenalty", 0.18, ...
        "weakTexturePenalty", 0.16, ...
        "regexExactBonus", 0.10, ...
        "regexPartialBonus", 0.04);

    config.heuristic = struct( ...
        "minConfidence", 0.55, ...
        "vehicleRoiScale", 2.8);

    config.gui = struct( ...
        "windowTitle", "Malaysian LPR + State Identification", ...
        "defaultVisible", "on");

    config.debug = struct( ...
        "saveIntermediateImages", false, ...
        "verbose", true, ...
        "showPreprocessingFigure", false);

    config.malaysiaRules = malaysiaPlateRules();
end
