function rules = malaysiaPlateRules()
%MALAYSIAPLATERULES Registration rules used for state/category inference.

rules = struct( ...
    "name", {}, ...
    "category", {}, ...
    "matcherType", {}, ...
    "token", {}, ...
    "priority", {}, ...
    "description", {});

rules(end+1) = localRule("Military", "Military", "pattern", "^Z[A-Z0-9]+$", 100, ...
    "Military registration series.");
rules(end+1) = localRule("Diplomatic Corps", "Diplomatic", "pattern", "^[0-9]{1,3}DC[0-9A-Z]*$", 95, ...
    "Diplomatic registration series.");

rules(end+1) = localRule("Putrajaya", "Federal Territory", "prefix", "F", 90, ...
    "Federal Territory of Putrajaya.");
rules(end+1) = localRule("Kuala Lumpur", "Federal Territory", "prefix", "V", 90, ...
    "Federal Territory of Kuala Lumpur.");
rules(end+1) = localRule("Kuala Lumpur", "Federal Territory", "prefix", "W", 90, ...
    "Federal Territory of Kuala Lumpur.");
rules(end+1) = localRule("Labuan", "Federal Territory", "prefix", "L", 90, ...
    "Federal Territory of Labuan.");

rules(end+1) = localRule("Perak", "State Series", "prefix", "A", 80, ...
    "Perak registration prefix.");
rules(end+1) = localRule("Selangor", "State Series", "prefix", "B", 80, ...
    "Selangor registration prefix.");
rules(end+1) = localRule("Pahang", "State Series", "prefix", "C", 80, ...
    "Pahang registration prefix.");
rules(end+1) = localRule("Kelantan", "State Series", "prefix", "D", 80, ...
    "Kelantan registration prefix.");
rules(end+1) = localRule("Johor", "State Series", "prefix", "J", 80, ...
    "Johor registration prefix.");
rules(end+1) = localRule("Kedah", "State Series", "prefix", "K", 80, ...
    "Kedah registration prefix.");
rules(end+1) = localRule("Melaka", "State Series", "prefix", "M", 80, ...
    "Melaka registration prefix.");
rules(end+1) = localRule("Negeri Sembilan", "State Series", "prefix", "N", 80, ...
    "Negeri Sembilan registration prefix.");
rules(end+1) = localRule("Pulau Pinang", "State Series", "prefix", "P", 80, ...
    "Pulau Pinang registration prefix.");
rules(end+1) = localRule("Perlis", "State Series", "prefix", "R", 80, ...
    "Perlis registration prefix.");
rules(end+1) = localRule("Sabah", "State Series", "prefix", "S", 80, ...
    "Sabah registration prefix.");
rules(end+1) = localRule("Terengganu", "State Series", "prefix", "T", 80, ...
    "Terengganu registration prefix.");
rules(end+1) = localRule("Sarawak", "State Series", "prefix", "Q", 80, ...
    "Sarawak registration prefix.");

rules = sortrows(struct2table(rules), "priority", "descend");
rules = table2struct(rules);
end

function rule = localRule(name, category, matcherType, token, priority, description)
rule = struct( ...
    "name", string(name), ...
    "category", string(category), ...
    "matcherType", string(matcherType), ...
    "token", string(token), ...
    "priority", priority, ...
    "description", string(description));
end

