function config = motorScenePreset(rootDir)
    % MOTORSCENEPRESET Config overrides tuned for motorcycle rear shots (two-row plates,
    % plate often lower in frame, more cluttered background than typical car images).

    if nargin < 1 || strlength(string(rootDir)) == 0
        rootDir = fileparts(fileparts(fileparts(mfilename("fullpath"))));
    end

    % Down-rank edge blobs on frame clutter; up-rank text-threshold branches (white on black).
    branchAdjustments = containers.Map( ...
        {'edge_full', 'edge_priority', 'text_dark_priority', 'text_priority', 'dark_priority', 'mser_text'}, ...
        {-0.08, -0.07, 0.10, 0.06, 0.04, -0.05});

    motorWeights = struct( ...
        "detector", 0.13, ...
        "plateEvidence", 0.21, ...
        "recognition", 0.13, ...
        "regex", 0.23, ...
        "state", 0.12, ...
        "composition", 0.07, ...
        "length", 0.04, ...
        "structure", 0.11, ...
        "framing", 0.06);

    config = validateConfig(struct( ...
        "detection", struct( ...
            "scales", [0.72 0.88 1.0 1.15 1.35 1.65 2.0 2.35], ...
            "priorityRoi", [0.05 0.26 0.96 0.985], ...
            "targetVerticalCenterRatio", 0.68, ...
            "minVerticalCenterRatio", 0.12, ...
            "maxVerticalCenterRatio", 0.97, ...
            "focusPenaltyWeight", 0.15, ...
            "focusPenaltyThreshold", 0.37, ...
            "mserEnabled", false, ...
            "maxCandidatesToKeep", 48, ...
            "darkRoiPercentile", 35, ...
            "textClusterBinarizeSensitivity", 0.38, ...
            "branchAdjustments", branchAdjustments, ...
            "closeKernel", [4 16], ...
            "openKernel", [2 6], ...
            "dilateKernel", [3 11]), ...
        "classification", struct( ...
            "allowSuffixLetter", false), ...
        "reranking", struct( ...
            "maxCandidatesToEvaluate", 14, ...
            "weights", motorWeights, ...
            "substringOverlapThreshold", 0.36, ...
            "invalidPrefixPenalty", 0.24, ...
            "weakFramingPenalty", 0.11, ...
            "weakTexturePenalty", 0.28, ...
            "implausibleLengthPenalty", 0.10), ...
        "pipeline", struct( ...
            "snapOcrToFilenameWhenClose", true, ...
            "snapOcrMaxEditDistance", 4, ...
            "snapOcrMaxRelativeDistance", 0.48)));
end
