function grayImage = renderTextImage(textValue, canvasSize, varargin)
%RENDERTEXTIMAGE Render text to a grayscale image using base MATLAB graphics.

parser = inputParser();
addRequired(parser, "textValue", @(x) ischar(x) || isstring(x));
addRequired(parser, "canvasSize", @(x) isnumeric(x) && numel(x) == 2);
addParameter(parser, "FontName", "Consolas", @(x) ischar(x) || isstring(x));
addParameter(parser, "FontSize", 28, @(x) isnumeric(x) && isscalar(x));
parse(parser, textValue, canvasSize, varargin{:});

canvasSize = double(parser.Results.canvasSize);
fig = figure( ...
    "Visible", "off", ...
    "Color", "white", ...
    "MenuBar", "none", ...
    "ToolBar", "none", ...
    "Position", [100 100 canvasSize(2) canvasSize(1)]);
cleanup = onCleanup(@() delete(fig)); %#ok<NASGU>

ax = axes(fig, ...
    "Units", "normalized", ...
    "Position", [0 0 1 1], ...
    "Color", "white", ...
    "XColor", "white", ...
    "YColor", "white");
axis(ax, [0 1 0 1]);
axis(ax, "off");

text(ax, 0.5, 0.5, char(string(textValue)), ...
    "Units", "normalized", ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", ...
    "FontName", char(string(parser.Results.FontName)), ...
    "FontSize", parser.Results.FontSize, ...
    "Color", "black", ...
    "Interpreter", "none");

frame = getframe(ax);
captured = frame2im(frame);
grayImage = im2gray(captured);
grayImage = imresize(grayImage, canvasSize);
end
