function showEvaluatedCandidateSummary(evaluatedCandidates, config)
%SHOWEVALUATEDCANDIDATESUMMARY Print top reranked candidates to the command window.

    displayCount = min(localDisplayCount(config), numel(evaluatedCandidates));
    records = evaluatedCandidates(1:displayCount);

    summary = table( ...
        (1:displayCount).', ...
        [records.finalScore].', ...
        [records.detectorScore].', ...
        [records.plateEvidenceScore].', ...
        [records.recognitionScore].', ...
        [records.regexScore].', ...
        [records.stateScore].', ...
        [records.compositionScore].', ...
        [records.lengthScore].', ...
        [records.structureScore].', ...
        [records.framingScore].', ...
        [records.textLength].', ...
        string({records.recognitionPath}).', ...
        string({records.profileName}).', ...
        string({records.layoutHint}).', ...
        string({records.branchName}).', ...
        string({records.recognizedText}).', ...
        string(arrayfun(@(r) r.stateInfo.name, records, "UniformOutput", false)).', ...
        'VariableNames', { ...
            'Rank', 'FinalScore', 'Detector', 'PlateEvidence', 'Recognition', ...
            'Regex', 'State', 'Composition', 'LengthScore', 'Structure', 'Framing', 'TextLength', ...
            'Path', 'Profile', 'Layout', 'Branch', ...
            'RecognizedText', 'StateName'});

    disp("=== Evaluated Candidate Summary ===");
    disp(summary);
end

function count = localDisplayCount(config)
    count = 12;
    if isfield(config, "debug") && isfield(config.debug, "maxEvaluatedCandidatesToDisplay")
        count = max(1, round(double(config.debug.maxEvaluatedCandidatesToDisplay)));
    end
end
