function showEvaluatedCandidateDebugFigure(evaluatedCandidates, config)
%SHOWEVALUATEDCANDIDATEDEBUGFIGURE Show top reranked candidates with OCR details.

    displayCount = min(localDisplayCount(config), numel(evaluatedCandidates));
    records = evaluatedCandidates(1:displayCount);

    figureHandle = findall(groot, "Type", "figure", "Tag", "LPREvaluatedCandidatesDebug");
    if isempty(figureHandle) || ~isvalid(figureHandle(1))
        figureHandle = figure( ...
            "Name", "LPR Evaluated Candidates", ...
            "NumberTitle", "off", ...
            "Tag", "LPREvaluatedCandidatesDebug");
    else
        figureHandle = figureHandle(1);
        clf(figureHandle);
        figure(figureHandle);
    end

    tileCols = min(4, displayCount);
    tileRows = ceil(displayCount / tileCols);
    tiledlayout(figureHandle, tileRows, tileCols, ...
        "TileSpacing", "compact", ...
        "Padding", "compact");

    for i = 1:displayCount
        nexttile;
        displayImage = localDisplayImage(records(i));
        imshow(displayImage);
        title(sprintf([ ...
            '#%d %.3f | Det %.2f Plate %.2f OCR %.2f\n' ...
            'Regex %.2f | State %.2f | Len %.2f\n' ...
            'Struct %.2f | Frame %.2f\n' ...
            '%s | %s | %s\n' ...
            'Text %s'], ...
            i, ...
            records(i).finalScore, ...
            records(i).detectorScore, ...
            records(i).plateEvidenceScore, ...
            records(i).recognitionScore, ...
            records(i).regexScore, ...
            records(i).stateScore, ...
            records(i).lengthScore, ...
            records(i).structureScore, ...
            records(i).framingScore, ...
            char(string(records(i).recognitionPath)), ...
            char(string(records(i).profileName)), ...
            char(string(records(i).branchName)), ...
            char(localDisplayText(records(i).recognizedText))), ...
            "FontSize", 8, ...
            "Interpreter", "none");
    end
end

function imageOut = localDisplayImage(record)
    if isfield(record, "ocrInputPlate") && ~isempty(record.ocrInputPlate)
        imageOut = record.ocrInputPlate;
    elseif isfield(record, "rectifiedPlate") && ~isempty(record.rectifiedPlate)
        imageOut = record.rectifiedPlate;
    else
        imageOut = zeros(40, 120, "uint8");
    end
end

function textOut = localDisplayText(textIn)
    textOut = string(textIn);
    if strlength(textOut) == 0
        textOut = "<empty>";
        return;
    end

    if strlength(textOut) > 14
        textOut = extractBefore(textOut, 15) + "...";
    end
end

function count = localDisplayCount(config)
    count = 12;
    if isfield(config, "debug") && isfield(config.debug, "maxEvaluatedCandidatesToDisplay")
        count = max(1, round(double(config.debug.maxEvaluatedCandidatesToDisplay)));
    end
end
