function showDetectionCandidateDebugFigure(grayImage, candidateRecords, config)
%SHOWDETECTIONCANDIDATEDEBUGFIGURE Show top plate candidates with scores and key metrics.

    displayCount = min(localDisplayCount(config), numel(candidateRecords));
    records = candidateRecords(1:displayCount);

    figureHandle = findall(groot, "Type", "figure", "Tag", "LPRDetectionCandidatesDebug");
    if isempty(figureHandle) || ~isvalid(figureHandle(1))
        figureHandle = figure( ...
            "Name", "LPR Detection Candidates", ...
            "NumberTitle", "off", ...
            "Tag", "LPRDetectionCandidatesDebug");
    else
        figureHandle = figureHandle(1);
        clf(figureHandle);
        figure(figureHandle);
    end

    tileCols = min(4, displayCount);
    tileRows = ceil(displayCount / tileCols);
    tiledlayout(figureHandle, tileRows, tileCols, ...
        "TileSpacing", "compact", ...
        "Padding", "compact");

    for i = 1:displayCount
        nexttile;
        candidateImage = imcrop(grayImage, records(i).bbox);
        if isempty(candidateImage)
            candidateImage = grayImage;
        end

        imshow(candidateImage);
        title(sprintf([ ...
            '#%d %.3f | %s | %s\n' ...
            'AR %.2f A %.4f W %.3f H %.3f\n' ...
            'E %.2f C %.2f T %.2f P %.2f Al %.2f'], ...
            i, ...
            records(i).score, ...
            char(records(i).branchName), ...
            char(records(i).profileName), ...
            records(i).aspectRatio, ...
            records(i).areaRatio, ...
            records(i).widthRatio, ...
            records(i).heightRatio, ...
            records(i).edgeDensity, ...
            records(i).contrastScore, ...
            records(i).characterTextureScore, ...
            records(i).plateContrastScore, ...
            records(i).componentAlignmentScore), ...
            "FontSize", 8, ...
            "Interpreter", "none");
    end
end

function count = localDisplayCount(config)
    count = 12;
    if isfield(config, "debug") && isfield(config.debug, "maxDetectionCandidatesToDisplay")
        count = max(1, round(double(config.debug.maxDetectionCandidatesToDisplay)));
    end
end
