function showDetectionCandidateSummary(candidateRecords, config)
%SHOWDETECTIONCANDIDATESUMMARY Print top detection candidates to the command window.

    displayCount = min(localDisplayCount(config), numel(candidateRecords));
    records = candidateRecords(1:displayCount);

    summary = table( ...
        (1:displayCount).', ...
        [records.score].', ...
        string({records.branchName}).', ...
        string({records.profileName}).', ...
        string({records.layoutHint}).', ...
        [records.rowCountEstimate].', ...
        [records.aspectRatio].', ...
        [records.areaRatio].', ...
        [records.widthRatio].', ...
        [records.heightRatio].', ...
        [records.edgeDensity].', ...
        [records.contrastScore].', ...
        [records.characterTextureScore].', ...
        [records.plateContrastScore].', ...
        [records.componentAlignmentScore].', ...
        [records.emptyRegionPenalty].', ...
        [records.textComponentCount].', ...
        'VariableNames', { ...
            'Rank', 'Score', 'Branch', 'Profile', 'Layout', 'Rows', 'Aspect', 'AreaRatio', ...
            'WidthRatio', 'HeightRatio', 'EdgeDensity', 'Contrast', ...
            'CharTexture', 'PlateContrast', 'Alignment', 'EmptyPenalty', 'TextCount'});

    disp("=== Detection Candidate Summary ===");
    disp(summary);
end

function count = localDisplayCount(config)
    count = 12;
    if isfield(config, "debug") && isfield(config.debug, "maxDetectionCandidatesToDisplay")
        count = max(1, round(double(config.debug.maxDetectionCandidatesToDisplay)));
    end
end
